include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
  errors:
    missing_required_param: error
    prefer_const_constructors: error
    curly_braces_in_flow_control_structures: error
    missing_return: warning
    todo: ignore
    prefer_single_quotes: ignore
    omit_local_variable_types: ignore
    prefer_conditional_assignment: ignore
    prefer_if_null_operators: ignore
    prefer_collection_literals: ignore
    prefer_final_fields: ignore
    prefer_for_elements_to_map_fromiterable: ignore
    prefer_generic_function_type_aliases: ignore
    prefer_spread_collections: ignore
    sort_child_properties_last: ignore
    unnecessary_brace_in_string_interps: ignore
exclude:
  - lib/**/*.freezed.dart

linter:
  rules:
    - avoid_classes_with_only_static_members
    - avoid_void_async
    - avoid_unused_constructor_parameters
    - await_only_futures
    - directives_ordering
    - no_runtimeType_toString
    - prefer_typing_uninitialized_variables
    - unnecessary_overrides
    - unnecessary_string_interpolations
    - prefer_const_constructors