name: Deploy Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        include:
          - os: ubuntu-18.04
            TARGET: linux

    steps:
    - name: Install Linux dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config libreadline-dev
    
    - name: Clone Flutter repository with stable channel
      uses: actions/checkout@v2
      with:
        repository: 'flutter/flutter'
        ref: '2.0.6'
        path: 'flutter'
        fetch-depth: 0

    - name: Add Flutter to the PATH for Unix
      run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
      if: runner.os != 'Windows'
    - name: Run Flutter doctor
      run: flutter doctor -v

    - name: Configure and Clone
      env:
        PUBLISH_EMAIL: ${{secrets.PUBLISH_EMAIL}}
        PUBLISH_USERNAME: ${{secrets.PUBLISH_USERNAME}}
        WAVEFORM_BOT_PAT: ${{secrets.WAVEFORM_BOT_PAT}}
      run: |
        git config --global user.email "$PUBLISH_EMAIL"
        git config --global user.name "$PUBLISH_USERNAME"
        git clone https://$PUBLISH_USERNAME:$WAVEFORM_BOT_PAT@github.com/hydro-sdk/registry.git

    - name: Get packages for Registry Dart
      run: flutter pub get
      working-directory: registry

    - name: Build
      run: export REGISTRY_TEST_SCHEME=${{ secrets.REGISTRY_TEST_SCHEME }} REGISTRY_TEST_HOST=${{ secrets.REGISTRY_TEST_HOST }}; flutter build web -t lib/main_prod.dart
      working-directory: registry
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.WAVEFORM_BOT_PAT}}
        publish_dir: ./registry/build/web